image: node:latest

stages:
  - test
  - release

cache:
  paths:
    - node_modules/

before_script:
  - yarn install

test:
  stage: test
  script:
    - yarn lint
    - yarn build
    - yarn test

release:
  stage: release
  script:
    - git config --global user.email "ci@example.com"
    - git config --global user.name "GitLab CI"
    - git remote set-url origin https://${CI_DEPLOY_USER}:${CI_DEPLOY_PASSWORD}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
    - git checkout $CI_COMMIT_REF_NAME
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
    - chmod +x ./newVersion.sh
    - ./newVersion.sh "${CI_COMMIT_MESSAGE:-Автоматическое обновление версии через CI}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "release" && $CI_COMMIT_AUTHOR !~ /^GitLab CI/'
      when: always
    - when: never