export * from './commonEntities'
export * from './types'
export * from './defaultCatalogs'
export * from './modules'
export * from './builders'
export * from './builders'
export {default as getProjectSpec} from './generators/fileTemplates/back/environment/docs/spec/getProjectSpec'
export {default as generateProject} from './generateProject'
