import { expect } from 'jest-without-globals'
import CatalogBuilder from './builders/CatalogBuilder'

// yarn test -t CatalogBuilder-serialization

describe.skip('CatalogBuilder-serialization', () => {
  const cards = new CatalogBuilder('cards', 'ru')
  cards.addField('name').setType('string').setRequired()
  cards.addField('lastDigits').setType('int').setRequired()
  cards.addField('active').setType('bool')

  test('getObject', () => {
    expect(cards.build()).toMatchObject({
      name: 'cards',
      singleKey: true,
      fields: [
        {
          name: 'id',
          type: 'int',
          required: true,
          autoGenerated: true,
        },
        {
          name: 'name',
          type: 'string',
          required: true,
        },
        {
          name: 'lastDigits',
          type: 'int',
          required: true,
        },
        {
          name: 'active',
          type: 'bool',
          required: false,
        },
      ],
    })
  })

  test('fromObject', () => {
    const fromObj = CatalogBuilder.fromObject(
      {
        fields: [
          {
            name: 'id',
            type: 'string',
            required: true,
          },
          {
            name: 'name',
            type: 'string',
            required: true,
          },
          {
            name: 'lastDigits',
            type: 'int',
            required: true,
          },
          {
            name: 'active',
            type: 'bool',
            required: false,
          },
        ],
        name: 'cards',
      },
      'ru'
    )
    expect(fromObj.build()).toMatchObject({
      fields: [
        {
          name: 'id',
          type: 'string',
          required: true,
        },
        {
          name: 'name',
          type: 'string',
          required: true,
        },
        {
          name: 'lastDigits',
          type: 'int',
          required: true,
        },
        {
          name: 'active',
          type: 'bool',
          required: false,
        },
      ],
      name: 'cards',
    })
  })
})
