import {
  ConstantOnCreateInt,
  ConstantOnUpdateInt,
  IdField,
  TKeyFieldType,
} from '../buildedTypes'
import { BaseFieldBuilder } from './BaseFieldBuilder'

export class IdFieldBuilder extends BaseFieldBuilder {
  type: TKeyFieldType = 'int'
  autoGenerated = true
  constructor(name: string, defaultLanguage: string, title?: string) {
    super(name, defaultLanguage, title)
    this.required = true
    this.updateDefaultDbValue()
  }

  setType(type: TKeyFieldType) {
    this.type = type

    if (this.type === 'string') {
      this.autoGenerated = false
      this.defaultDbValue = undefined
    }

    this.updateDefaultDbValue()

    return this
  }

  build(): IdField {
    const base = {
      needFor: this.needFor,
      hidden: this.hidden,
      name: this.name,
      required: this.required,
      requiredOnInput: this.requiredOnInput,
      updatable: this.updatable,
      updatableByUser: this.updatableByUser,
      searchable: this.searchable,
    }

    if (this.type === 'bigint' || this.type === 'int') {
      return {
        ...base,
        autoGenerated: this.autoGenerated,
        category: 'id',
        constantOnCreate: this.constantOnCreate as ConstantOnCreateInt,
        constantOnUpdate: this.constantOnUpdate as ConstantOnUpdateInt,
        type: this.type,
        title: this.title,
        showInList: this.showInList,
        showInCreate: this.showInCreate,
        showInEdit: this.showInEdit,
        defaultDbValue: this.defaultDbValue,
      }
    } else if (this.type === 'string') {
      return {
        ...base,
        autoGenerated: this.autoGenerated,
        category: 'id',
        type: this.type,
        title: this.title,
        showInList: this.showInList,
        showInCreate: this.showInCreate,
        showInEdit: this.showInEdit,
        defaultDbValue: this.defaultDbValue,
        stringType: this.stringType,
      }
    }

    throw new Error(`Unexpected type: ${this.type}`)
  }
  setAutoGenerated(autoGenerated = true) {
    this.autoGenerated = autoGenerated
    this.updateDefaultDbValue()
    if (!autoGenerated) {
      this.defaultDbValue = undefined
    }

    return this
  }
  private updateDefaultDbValue() {
    if (this.autoGenerated) {
      if (this.type === 'bigint' || this.type === 'int') {
        this.defaultDbValue = 'autoincrement()'
      } else {
        this.defaultDbValue = 'cuid()'
      }
    }

    return this
  }
  setNotAutoGenerated() {
    this.autoGenerated = false

    return this
  }
}
