import { expect } from 'jest-without-globals'
import IdFieldBuilder from '../../../../builders/fields/IdFieldBuilder'
import { genPrismaIdField } from './genPrismaIdField'

// yarn test --testPathPattern genPrismaIdField

describe('genPrismaIdField', () => {
  test('int autogenerated', () => {
    const someField = new IdFieldBuilder('someField', 'ru')
      .setType('bigint')
      .setAutoGenerated(true)
      .build()
    expect(genPrismaIdField(someField)).toEqual([
      '  someField  BigInt  @default(autoincrement())  @id'.replaceAll(
        /\s+/gu,
        '\t'
      ),
    ])
  })
  test('int not autogenerated', () => {
    const someField = new IdFieldBuilder('someField', 'ru')
      .setType('bigint')
      .setAutoGenerated(false)
      .build()
    expect(genPrismaIdField(someField)).toEqual([
      '  someField  BigInt  @id'.replaceAll(/\s+/gu, '\t'),
    ])
  })
  test('string autogenerated', () => {
    const someField = new IdFieldBuilder('someField', 'ru')
      .setType('string')
      .setAutoGenerated(true)
      .build()
    expect(genPrismaIdField(someField)).toEqual([
      '  someField  String  @default(cuid())  @id'.replaceAll(/\s+/gu, '\t'),
    ])
  })
  test('string not autogenerated', () => {
    const someField = new IdFieldBuilder('someField', 'ru')
      .setType('string')
      .setAutoGenerated(false)
      .build()
    expect(genPrismaIdField(someField)).toEqual([
      '  someField  String  @id'.replaceAll(/\s+/gu, '\t'),
    ])
  })
})
