/* eslint-disable max-len */
import { singular } from 'pluralize'

import { Entity } from '../../../../../builders'
import { EntityWideGenerationArgs } from '../../../../../args'
import { getKeyField } from '../../../../../metaUtils'
import * as R from 'ramda'
import { camelSingular } from '../../../../../../utils/cases'
import { generatedWarning } from '../../../../../utils'

const getNames = R.map(R.path(['name']));

const autogeneratedStringId = (entity: Entity) =>
  getKeyField(entity).autoGenerated && getKeyField(entity).type === 'string'

export const configTmpl = ({
  entity,
  options,
}: EntityWideGenerationArgs) => {
  const forbiddenForUserFields = entity.fields.filter(
    (f) => !f.updatableByUser && f.name !== 'search'
  )

  const searchableFields = entity.fields.filter((f) => f.searchable)
  const dateFields = searchableFields.filter((f) =>
    ['date', 'datetime'].includes(f.type)
  )
  const notDateFields = searchableFields.filter(
    (f) => !['date', 'datetime'].includes(f.type)
  )

  const config: Record<string, any> = {
    idType: getKeyField(entity).type,
    autogeneratedStringId: autogeneratedStringId(entity),
    auditable: entity.auditable,
    withSearch: ['catalog', 'document'].includes(entity.type),
    externalSearch: entity.externalSearch,
    dateFields: getNames(dateFields),
    otherFields: getNames(notDateFields),
    forbiddenForUserFields: getNames(forbiddenForUserFields),
    entityTypeId: camelSingular(entity.name),
  };

  if (entity.type === 'document') {
    config.registries = entity.registries.map((registry) => singular(registry));
    config.registrarTypeId = singular(entity.name);
  }

  const configType = entity.type === 'document' ? 'DocumentConfig' : 'ServiceConfig';

  return `/* eslint-disable quote-props,comma-dangle */
import {${configType}} from '../types';
${options.skipWarningThisIsGenerated ? '' : `
// ${generatedWarning}`}

const config: ${configType} = ${JSON.stringify(config, undefined, '  ').replaceAll('"', '\'')};

export default config;
`;
}
