/* eslint-disable max-len */
import { fieldTypeToTsType } from '../../../../fieldTypeToTsType'
import {
  pascalPlural,
  pascalSingular,
  camelSingular,
} from '../../../../../../utils/cases'
import { Entity } from '../../../../../builders/buildedTypes'
import { EntityWideGenerationArgs } from '../../../../../args'
import { addComma, generatedWarning, pad1, pad3 } from '../../../../../utils'
import { getKeyField } from '../../../../../metaUtils'
import { pathCase } from 'change-case'

const autogeneratedStringId = (entity: Entity) =>
  getKeyField(entity).autoGenerated && getKeyField(entity).type === 'string'

export const prismaServiceTmpl = ({
  entity,
  options,
}: EntityWideGenerationArgs) => {
  const contextName = 'Context'

  const forbiddenForUserFields = entity.fields.filter(
    (f) => !f.updatableByUser && f.name !== 'search'
  )
  const requiredForDbButNotForUserFields = entity.fields.filter(
    (f) => f.required && !f.requiredOnInput && f.name !== 'id'
  )

  // const notRequiredOnInputFields: ScalarField[] = entity.fields.filter(f => ['scalar', 'link'].includes(f.category) && !f.requiredOnInput && f.name !== 'search') as ScalarField[];

  // const notRequiredOnInputFields: ScalarField[] = entity.fields.filter(f => f.category === 'scalar' && !f.updatableByUser) as ScalarField[];

  const getDefaultableFields = () =>
    entity.fields
      .filter((f) => f.defaultBackendValueExpression)
      .filter((f) => !f.hidden)

  const getDefaultValues = () =>
    getDefaultableFields().map(
      (f) => `${f.name}: ${f.defaultBackendValueExpression}`
    )

  const searchableFields = entity.fields.filter((f) => f.searchable)
  const dateFields = searchableFields.filter((f) =>
    ['date', 'datetime'].includes(f.type)
  )
  const notDateFields = searchableFields.filter(
    (f) => !['date', 'datetime'].includes(f.type)
  )

  const getDefaultValuesWithSearchJoined = (initialObjectName: string) => {
    const defaultValues = getDefaultValues()

    if (['catalog', 'document'].includes(entity.type)) {
      defaultValues.push(`search: getSearchString(${initialObjectName})`)
    }

    return defaultValues.map(addComma).join('\n')
  }

  return `import {
  ListMetadata,
  MutationCreate${pascalSingular(entity.name)}Args,
  MutationUpdate${pascalSingular(entity.name)}Args,
  MutationRemove${pascalSingular(entity.name)}Args,
  QueryAll${pascalPlural(entity.name)}Args,
  Query_All${pascalPlural(entity.name)}MetaArgs,
  ${pascalSingular(entity.name)},
  ${pascalSingular(entity.name)}Filter,
} from '../../../generated/graphql';
import {toPrismaRequest} from '../../../utils/prisma/toPrismaRequest';
import {${contextName}} from '../types';${
    entity.type === 'document'
      ? `
import {Prisma, PrismaPromise} from '@prisma/client';`
      : `
import {Prisma} from '@prisma/client';`
  }
import {Additional${pascalPlural(
    entity.name
  )}Methods, getAdditionalMethods} from './additionalMethods';
import initUserHooks from './initUserHooks';
import initBuiltInHooks from './initBuiltInHooks';
import {getHooksUtils, HooksAddType} from '../getHooksUtils';
import * as R from 'ramda';${
    autogeneratedStringId(entity)
      ? `
import {v4 as uuidv4} from 'uuid';`
      : ''
  }${
    entity.type === 'document'
      ? `
import {getUnPostOperations} from './hooks/getUnPostOperations';
import {${pascalSingular(
          entity.name
        )}RegistryEntries, getPostOperations} from './hooks/getPostOperations';
import {getRegistryEntries} from './hooks/getRegistryEntries';`
      : ''
  }${
    entity.auditable
      ? `
import Entity from '../../../types/Entity';`
      : ''
  }${
    entity.externalSearch
      ? `
import {toElasticRequest} from '../../../utils/toElasticRequest';`
      : `
import {toPrismaTotalRequest} from '../../../utils/prisma/toPrismaTotalRequest';`
  }
import {DefinedFieldsInRecord, DefinedRecord, PartialFieldsInRecord} from '../../../types/utils';
import getSearchStringCreator from '../utils/getSearchStringCreator';
${
  options.skipWarningThisIsGenerated
    ? ''
    : `
// ${generatedWarning}
`
}
const forbiddenForUserFields: string[] = ${
    forbiddenForUserFields.length > 0
      ? `[
${pad1(forbiddenForUserFields.map((f) => `'${f.name}',`).join('\n'))}
];`
      : '[];'
  }
${
  entity.type === 'infoRegistry' && entity.period !== 'notPeriodic'
    ? `
export type Slice${pascalPlural(entity.name)}Filter = QueryAll${pascalPlural(
        entity.name
      )}Args['filter'];
`
    : ''
}
export type Autodefinable${pascalSingular(entity.name)}Keys = ${
    getDefaultableFields().length > 0
      ? `${getDefaultableFields()
          .map((f) => `'${f.name}'`)
          .join(' | ')}`
      : 'never'
  };
export type ForbidenForUser${pascalSingular(entity.name)}Keys = ${
    forbiddenForUserFields.length > 0
      ? `${forbiddenForUserFields.map((f) => `'${f.name}'`).join(' | ')}`
      : 'never'
  };
export type RequiredDbNotUser${pascalSingular(entity.name)}Keys = ${
    requiredForDbButNotForUserFields.length > 0
      ? `${requiredForDbButNotForUserFields
          .map((f) => `'${f.name}'`)
          .join(' | ')}`
      : 'never'
  };

export type Autodefinable${pascalSingular(
    entity.name
  )}Part = DefinedRecord<Pick<MutationCreate${pascalSingular(
    entity.name
  )}Args, Autodefinable${pascalSingular(entity.name)}Keys>>;

export type Reliable${pascalSingular(entity.name)}CreateUserInput =
  Omit<MutationCreate${pascalSingular(
    entity.name
  )}Args, ForbidenForUser${pascalSingular(entity.name)}Keys>
  & Autodefinable${pascalSingular(entity.name)}Part;

export type Allowed${pascalSingular(
    entity.name
  )}ForUserCreateInput = Omit<MutationCreate${pascalSingular(
    entity.name
  )}Args, ForbidenForUser${pascalSingular(entity.name)}Keys>;

export type StrictCreate${pascalSingular(
    entity.name
  )}Args = DefinedFieldsInRecord<MutationCreate${pascalSingular(
    entity.name
  )}Args, RequiredDbNotUser${pascalSingular(
    entity.name
  )}Keys> & Autodefinable${pascalSingular(entity.name)}Part;
export type StrictUpdate${pascalSingular(
    entity.name
  )}Args = DefinedFieldsInRecord<MutationUpdate${pascalSingular(
    entity.name
  )}Args, RequiredDbNotUser${pascalSingular(
    entity.name
  )}Keys> & Autodefinable${pascalSingular(entity.name)}Part;

export type StrictCreate${pascalSingular(
    entity.name
  )}ArgsWithoutAutodefinable = PartialFieldsInRecord<StrictCreate${pascalSingular(
    entity.name
  )}Args, Autodefinable${pascalSingular(entity.name)}Keys>;
export type MutationCreate${pascalSingular(
    entity.name
  )}ArgsWithoutAutodefinable = PartialFieldsInRecord<MutationCreate${pascalSingular(
    entity.name
  )}Args, Autodefinable${pascalSingular(entity.name)}Keys>;
export type MutationUpdate${pascalSingular(
    entity.name
  )}ArgsWithoutAutodefinable = PartialFieldsInRecord<MutationUpdate${pascalSingular(
    entity.name
  )}Args, Autodefinable${pascalSingular(entity.name)}Keys>;

export interface Base${pascalPlural(entity.name)}Methods {
  get: (id: ${fieldTypeToTsType(getKeyField(entity).type)}) =>
    Promise<${pascalSingular(entity.name)} | null>;
  getRequired: (id: ${fieldTypeToTsType(getKeyField(entity).type)}) =>
    Promise<${pascalSingular(entity.name)}>;
  all: (params?: QueryAll${pascalPlural(entity.name)}Args) =>
    Promise<${pascalSingular(entity.name)}[]>;
  findOne: (params?: QueryAll${pascalPlural(entity.name)}Args) =>
    Promise<${pascalSingular(entity.name)} | null>;
  findOneRequired: (params?: QueryAll${pascalPlural(entity.name)}Args) =>
    Promise<${pascalSingular(entity.name)}>;${
    entity.type === 'infoRegistry' && entity.period !== 'notPeriodic'
      ? `
  sliceOfTheLast: (date?: Date, filter?: Slice${pascalPlural(
    entity.name
  )}Filter) =>
    Promise<${pascalSingular(entity.name)} | null>;
  sliceOfTheFirst: (date?: Date, filter?: Slice${pascalPlural(
    entity.name
  )}Filter) =>
    Promise<${pascalSingular(entity.name)} | null>;`
      : ''
  }
  count: (params?: Query_All${pascalPlural(entity.name)}MetaArgs) =>
    Promise<number>;
  meta: (params?: Query_All${pascalPlural(entity.name)}MetaArgs) =>
    Promise<ListMetadata>;
  create: (data: MutationCreate${pascalSingular(
    entity.name
  )}ArgsWithoutAutodefinable, byUser?: boolean) =>
    Promise<${pascalSingular(entity.name)}>;
  createMany: (data: StrictCreate${pascalSingular(
    entity.name
  )}ArgsWithoutAutodefinable[], byUser?: boolean) =>
    Promise<Prisma.BatchPayload>;
  update: ({id, ...rest}: MutationUpdate${pascalSingular(
    entity.name
  )}ArgsWithoutAutodefinable, byUser?: boolean) =>
    Promise<${pascalSingular(entity.name)}>;
  upsert: (
    data: PartialFieldsInRecord<MutationUpdate${pascalSingular(entity.name)}ArgsWithoutAutodefinable, 'id'>,
    byUser?: boolean,
  ) =>
    Promise<${pascalSingular(entity.name)}>;
  upsertAdvanced: (
    filter: ${pascalSingular(entity.name)}Filter,
    data: MutationCreate${pascalSingular(entity.name)}ArgsWithoutAutodefinable,
    byUser?: boolean,
  ) =>
    Promise<${pascalSingular(entity.name)}>;
  delete: (params: MutationRemove${pascalSingular(entity.name)}Args) =>
    Promise<${pascalSingular(entity.name)}>;${
    entity.type === 'document'
      ? `

  rePost: (id: number) =>
    Promise<void>;
  getRegistryEntries: (data: ${pascalSingular(entity.name)}) =>
    Promise<${pascalSingular(entity.name)}RegistryEntries>;
  getPostOperations: (data: ${pascalSingular(entity.name)}) =>
    Promise<PrismaPromise<any>[]>;
  getUnPostOperations: (id: number) =>
    Promise<PrismaPromise<any>[]>;`
      : ''
  }
}

export type ${pascalPlural(entity.name)}Service = Base${pascalPlural(
    entity.name
  )}Methods
  & Additional${pascalPlural(entity.name)}Methods
  & HooksAddType<
    ${pascalSingular(entity.name)},
    QueryAll${pascalPlural(entity.name)}Args,
    Reliable${pascalSingular(entity.name)}CreateUserInput,
    MutationUpdate${pascalSingular(entity.name)}Args,
    MutationRemove${pascalSingular(entity.name)}Args,
    StrictCreate${pascalSingular(entity.name)}Args,
    StrictUpdate${pascalSingular(entity.name)}Args
  >;

const dateFieldsForSearch: string[] = ${
    dateFields.length
      ? `[
${dateFields
  .map((f) => `'${f.name}',`)
  .map(pad1)
  .join('\n')}
];`
      : '[];'
  }

const otherFieldsForSearch: string[] = ${
    notDateFields.length
      ? `[
${notDateFields
  .map((f) => `'${f.name}',`)
  .map(pad1)
  .join('\n')}
];`
      : '[];'
  }

export const get${pascalPlural(entity.name)}Service = (ctx: ${contextName}) => {
  const {hooksAdd, runHooks} = getHooksUtils<
    ${pascalSingular(entity.name)},
    QueryAll${pascalPlural(entity.name)}Args,
    Reliable${pascalSingular(entity.name)}CreateUserInput,
    MutationUpdate${pascalSingular(entity.name)}Args,
    MutationRemove${pascalSingular(entity.name)}Args,
    StrictCreate${pascalSingular(entity.name)}Args,
    StrictUpdate${pascalSingular(entity.name)}Args
  >();

  const getSearchString = getSearchStringCreator(dateFieldsForSearch, otherFieldsForSearch);

  const augmentByDefault = async <T>(
    currentData: Record<string, any>,
  ): Promise<T & Autodefinable${pascalSingular(entity.name)}Part> => ${
    getDefaultableFields().length
      ? `{
    const defaultFieldConstructors = {
${pad3(
  getDefaultableFields()
    .map((f) => `${f.name}: async () => ${f.defaultBackendValueExpression}`)
    .map(addComma)
    .join('\n')
)}
    };

    const pairedConstructors = R.toPairs(defaultFieldConstructors);

    const resultedPairs: R.KeyValuePair<string, any>[] = [];
    for (const [key, constructor] of pairedConstructors) {
      resultedPairs.push([key, key in currentData && currentData[key] ? currentData[key] : await constructor()]);
    }

    return R.mergeLeft(currentData, R.fromPairs(resultedPairs)) as T & Autodefinable${pascalSingular(
      entity.name
    )}Part;
  }`
      : 'currentData as T'
  };

  const all = async (
    params: QueryAll${pascalPlural(entity.name)}Args = {},
  ): Promise<${pascalSingular(entity.name)}[]> => {${
    entity.externalSearch
      ? `
    const elasticSearch = ctx.elastic.createSearcher('${pathCase(
      entity.name
    )}');

    const search = await elasticSearch(toElasticRequest(await runHooks.changeListFilter(ctx, params)));

    const ids = search.hits.hits.map(el => BigInt((el._source as ${pascalSingular(
      entity.name
    )}).id));
    const prismaReq = toPrismaRequest(params, {noId: false});

    return ctx.prisma.${camelSingular(entity.name)}.findMany(
      {
        where: {id: {in: ids}},
        orderBy: prismaReq.orderBy,
      },`
      : `
    return ctx.prisma.${camelSingular(entity.name)}.findMany(
      toPrismaRequest(await runHooks.changeListFilter(ctx, params), {noId: false}),`
  }
    ) as unknown as Promise<${pascalSingular(entity.name)}[]>;
  };

  const findOne = async (
    params: QueryAll${pascalPlural(entity.name)}Args = {},
  ): Promise<${pascalSingular(entity.name)} | null> => {
    return ctx.prisma.${camelSingular(entity.name)}.findFirst(toPrismaRequest(
      await runHooks.changeListFilter(ctx, params),
      {noId: false},
    ));
  };

  const findOneRequired = async (
    params: QueryAll${pascalPlural(entity.name)}Args = {},
  ): Promise<${pascalSingular(entity.name)}> => {
    const found = await findOne(params);

    if (!found) {
      throw new Error(\`There is no entry with "\${JSON.stringify(params)}" filter\`);
    }

    return found;
  };

  const get = async (
    id: ${fieldTypeToTsType(getKeyField(entity).type)},
  ): Promise<${pascalSingular(entity.name)} | null> => {
    return findOne({filter: {id}});
  };

  const getRequired = async (
    id: ${fieldTypeToTsType(getKeyField(entity).type)},
  ): Promise<${pascalSingular(entity.name)}> => {
    const found = await get(id);

    if (!found) {
      throw new Error(\`There is no entry with "\${id}" id\`);
    }

    return found;
  };
${
  entity.type === 'infoRegistry' && entity.period !== 'notPeriodic'
    ? `
  const sliceOfTheLast = async (
    date?: Date,
    filter?: Slice${pascalPlural(entity.name)}Filter,
  ): Promise<${pascalSingular(entity.name)} | null> => {
    return ctx.prisma.${camelSingular(entity.name)}.findFirst(toPrismaRequest({
      sortField: 'date',
      sortOrder: 'desc',
      filter: {
        ...filter,
        date_lte: date ?? new Date(),
      },
    }, {noId: false}));
  };

  const sliceOfTheFirst = async (
    date?: Date,
    filter?: Slice${pascalPlural(entity.name)}Filter,
  ): Promise<${pascalSingular(entity.name)} | null> => {
    return ctx.prisma.${camelSingular(entity.name)}.findFirst(toPrismaRequest({
      sortField: 'date',
      sortOrder: 'asc',
      filter: {
        ...filter,
        date_gte: date ?? new Date(),
      },
    }, {noId: false}));
  };
`
    : ''
}
  const count = async (
    params: Query_All${pascalPlural(entity.name)}MetaArgs = {},
  ): Promise<number> => {${
    entity.externalSearch
      ? `
    const elasticCount = ctx.elastic.createCounter('${pathCase(entity.name)}');

    const reg = R.omit(['sortOrder', 'sortField'], toElasticRequest(await runHooks.changeListFilter(ctx, params)));

    const result = await elasticCount(reg);

    return result.count;
  };`
      : `
    return ctx.prisma.${camelSingular(
      entity.name
    )}.count(toPrismaTotalRequest(await runHooks.changeListFilter(ctx, params)));
  };`
  }

  const meta = async (
    params: Query_All${pascalPlural(entity.name)}MetaArgs = {},
  ): Promise<ListMetadata> => {
    return count(params).then(count => ({count}));
  };${
    options.readOnly
      ? ''
      : `${
          entity.type === 'document'
            ? `

  const post = async (
    data: ${pascalSingular(entity.name)},
  ): Promise<void> => {
    await ctx.prisma.$transaction(await getPostOperations(ctx, await augmentByDefault(data)));
  };`
            : ''
        }

  const create = async (
    data: MutationCreate${pascalSingular(entity.name)}ArgsWithoutAutodefinable,
    byUser = false,
  ): Promise<${pascalSingular(entity.name)}> => {
    // clear from fields forbidden for user
    const cleared = byUser ?
      R.omit(forbiddenForUserFields, data) as Allowed${pascalSingular(
        entity.name
      )}ForUserCreateInput :
      data;

    // Augment with default field
    const augmentedByDefault: Reliable${pascalSingular(
      entity.name
    )}CreateUserInput = await augmentByDefault(cleared);

    const processedData = await runHooks.beforeCreate(ctx, augmentedByDefault);
${
  autogeneratedStringId(entity)
    ? `
    const createOperation = ctx.prisma.${camelSingular(entity.name)}.create({
      data: {
        id: uuidv4(),
        ...R.mergeDeepLeft(
          processedData,
          ${
            ['catalog', 'document'].includes(entity.type)
              ? `{
            search: getSearchString(processedData),
          }`
              : '{}'
          }
        ),
      },
    });`
    : `
    const createOperation = ctx.prisma.${camelSingular(entity.name)}.create({
      data: R.mergeDeepLeft(
        processedData,
        ${
          ['catalog', 'document'].includes(entity.type)
            ? `{
          search: getSearchString(processedData),
        }`
            : '{}'
        },
      ),
    });`
}

    const operations = [
      createOperation,
      ...(await runHooks.additionalOperationsOnCreate(ctx, processedData)),
    ];

    const [result] = await ctx.prisma.$transaction(operations as any);
    if (!result) {
      throw new Error('There is no such entity');
    }

    await Promise.all([${
      getDefaultValuesWithSearchJoined('processedData')
        ? `
      // update search. earlier we does not have id
      ctx.prisma.${camelSingular(entity.name)}.update({
        where: {id: result.id},
        data: ${
          ['catalog', 'document'].includes(entity.type)
            ? `{
          search: getSearchString(result),
        }`
            : '{}'
        },
      }),`
        : ''
    }${
          entity.auditable
            ? `
      ctx.service('auditLogs').addCreateOperation({
        entityTypeId: Entity.${pascalSingular(entity.name)},
        entityId: result.id,
        actionData: data,
      }),`
            : ''
        }${
          entity.externalSearch
            ? `
      ctx.service('externalSearch').onEntityChange(Entity.${pascalSingular(
        entity.name
      )}, result.id.toString()),`
            : ''
        }${
          entity.type === 'document'
            ? `
      await ctx.prisma.$transaction(await getPostOperations(ctx, result)),`
            : ''
        }
    ]);

    await runHooks.afterCreate(ctx, result as ${pascalSingular(entity.name)});

    return result as ${pascalSingular(entity.name)};
  };

  const createMany = async (
    entries: StrictCreate${pascalSingular(
      entity.name
    )}ArgsWithoutAutodefinable[],
    byUser = false,
  ): Promise<Prisma.BatchPayload> => {
    // clear from fields forbidden for user
    const clearedData = byUser ? entries.map(data => R.omit(forbiddenForUserFields, data)) : entries;

    // Augment with default field
    const augmentedByDefault = await Promise.all(
      clearedData.map(el => augmentByDefault(el)),
    ) as StrictCreate${pascalSingular(entity.name)}Args[];
${
  autogeneratedStringId(entity)
    ? `
    const result = await ctx.prisma.${camelSingular(
      entity.name
    )}.createMany({data: augmentedByDefault.map(data => ({
      id: uuidv4(),
      ...R.mergeDeepLeft(
        data,
        ${
          ['catalog', 'document'].includes(entity.type)
            ? `{
          search: getSearchString(data),
        }`
            : '{}'
        },
      ),
    })), skipDuplicates: true});`
    : `
    const result = await ctx.prisma.${camelSingular(entity.name)}.createMany({
      data: augmentedByDefault.map(data => R.mergeDeepLeft(
        data,
        ${
          ['catalog', 'document'].includes(entity.type)
            ? `{
          search: getSearchString(data),
        }`
            : '{}'
        },
      )),
      skipDuplicates: true,
    });`
}

    if (!result) {
      throw new Error('There is no such entity');
    }

    return result;
  };

  const update = async (
    data: MutationUpdate${pascalSingular(entity.name)}ArgsWithoutAutodefinable,
    byUser = false,
  ): Promise<${pascalSingular(entity.name)}> => {
    // Get db version
    const dbVersion = await getRequired(data.id);

    // clear from fields forbidden for user
    const cleared = byUser ? R.omit(forbiddenForUserFields, data) : data;

    // Augment with default field
    const augmentedByDefault = await augmentByDefault(cleared);

    // augment data by fields from db
    const augmented: StrictUpdate${pascalSingular(
      entity.name
    )}Args = R.mergeLeft(augmentedByDefault, dbVersion);

    const processedData = await runHooks.beforeUpdate(ctx, augmented);

    const {id, ...rest} = processedData;

    const updateOperation = ctx.prisma.${camelSingular(entity.name)}.update({
      data: R.mergeDeepLeft(
        ${
          ['catalog', 'document'].includes(entity.type)
            ? `{
          search: getSearchString(processedData),
        }`
            : '{}'
        },
        rest,
      ),
      where: {id},
    });
${
  entity.auditable
    ? `
    const auditOperation = ctx.service('auditLogs').addUpdateOperation({
      entityTypeId: Entity.${pascalSingular(entity.name)},
      entityId: data.id,
      actionData: data,
    });
`
    : ''
}
    const operations = [
      updateOperation,${
        entity.auditable
          ? `
      auditOperation,`
          : ''
      }
      ...(await runHooks.additionalOperationsOnUpdate(ctx, processedData)),${
        entity.type === 'document'
          ? `
      ...(await getPostOperations(ctx, processedData)),`
          : ''
      }
    ];

    const [result] = await ctx.prisma.$transaction(operations as any);
    if (!result) {
      throw new Error('There is no such entity');
    }

    await Promise.all([${
      entity.externalSearch
        ? `
      ctx.service('externalSearch').onEntityChange(Entity.${pascalSingular(
        entity.name
      )}, data.id.toString()),`
        : ''
    }
      runHooks.afterUpdate(ctx, result as ${pascalSingular(entity.name)}),
    ]);

    return result as ${pascalSingular(entity.name)};
  };

  const upsert = async (
    data: PartialFieldsInRecord<MutationUpdate${pascalSingular(entity.name)}ArgsWithoutAutodefinable, 'id'>,
    byUser = false,
  ): Promise<${pascalSingular(entity.name)}> => {
    // Get db version
    const dbVersion = data.id ? await get(data.id) : null;

    // clear from fields forbidden for user
    const cleared = byUser ? R.omit(forbiddenForUserFields, data) : data;

    // Augment with default field
    const augmentedByDefault = await augmentByDefault(cleared);

    // augment data by fields from db
    const augmented: StrictUpdate${pascalSingular(entity.name)}Args =
      R.mergeLeft(augmentedByDefault, dbVersion || {} as ${pascalSingular(
        entity.name
      )});

    const processedData = await runHooks.beforeUpsert(ctx, {createData: augmented, updateData: augmented});
    const createData = {
      ...processedData.createData,
      search: getSearchString(processedData.createData),
    };
    const updateData = {
      ...processedData.updateData,
      search: getSearchString(processedData.updateData),
    };

    const result = await ctx.prisma.${camelSingular(entity.name)}.upsert({
      create: createData,
      update: updateData,
      where: {id: data.id},
    });

    if (!result) {
      throw new Error('There is no such entity');
    }
${
  entity.externalSearch
    ? `
    await ctx.service('externalSearch').onEntityChange(Entity.${pascalSingular(
      entity.name
    )}, result.id.toString());
`
    : ''
}
    return result;
  };

  const upsertAdvanced = async (
    filter: ${pascalSingular(entity.name)}Filter,
    data: MutationCreate${pascalSingular(entity.name)}ArgsWithoutAutodefinable,
    byUser = false,
  ): Promise<${pascalSingular(entity.name)}> => {
    const cnt = await count({filter});

    if (cnt > 1) {
      throw new Error(\`There is more then one entity (\${cnt}) that fits filter "$\{JSON.stringify(filter)}"\`);
    } else if (cnt === 0) {
      return create(data, byUser);
    } else {
      const dbVersion = await findOneRequired({filter});
      return update({...data, id: dbVersion.id}, byUser);
    }
  };

  const del = async (
    params: MutationRemove${pascalSingular(entity.name)}Args,
  ): Promise<${pascalSingular(entity.name)}> => {
    await runHooks.beforeDelete(ctx, params);

    const deleteOperation = ctx.prisma.${camelSingular(
      entity.name
    )}.delete({where: {id: params.id}});
${
  entity.auditable
    ? `
    const auditOperation = ctx.service('auditLogs').addDeleteOperation({
      entityTypeId: Entity.${pascalSingular(entity.name)},
      entityId: params.id,
    });
`
    : ''
}
    const operations = [
      deleteOperation,${
        entity.auditable
          ? `
      auditOperation,`
          : ''
      }
      ...(await runHooks.additionalOperationsOnDelete(ctx, params)),${
        entity.type === 'document'
          ? `
      ...(await getUnPostOperations(ctx, params.id)),`
          : ''
      }
    ];

    const entity = await get(params.id);

    if (!entity) {
      throw new Error(\`There is no entity with "\${params.id}" id\`);
    }

    const [result] = await ctx.prisma.$transaction(operations as any);

    if (!result) {
      throw new Error('There is no such entity');
    }

    await runHooks.afterDelete(ctx, entity);

    return entity;
  };${
    entity.type === 'document'
      ? `

  const rePost = async (
    id: number,
  ): Promise<void> => {
    const data = await get(id);

    if (!data) {
      throw new Error(\`There is no document with "\${id}" id\`);
    }

    await post(data);
  };`
      : ''
  }`
  }

  const baseMethods: Base${pascalPlural(entity.name)}Methods = {
    get,
    getRequired,
    all,
    findOne,
    findOneRequired,${
      entity.type === 'infoRegistry' && entity.period !== 'notPeriodic'
        ? `
    sliceOfTheLast,
    sliceOfTheFirst,`
        : ''
    }
    count,
    meta,
    create,
    createMany,
    update,
    upsert,
    upsertAdvanced,
    delete: del,${
      entity.type === 'document'
        ? `

    rePost,
    getRegistryEntries: (data: ${pascalSingular(
      entity.name
    )}) => getRegistryEntries(ctx, data),
    getPostOperations: async (data: ${pascalSingular(
      entity.name
    )}) => getPostOperations(ctx, await augmentByDefault(data)),
    getUnPostOperations: (id: number) => getUnPostOperations(ctx, id),`
        : ''
    }
  };

  const additionalMethods = getAdditionalMethods(ctx, baseMethods);

  const service: ${pascalPlural(entity.name)}Service = {
    ...baseMethods,
    ...additionalMethods,
    hooksAdd,
  };

  initBuiltInHooks(service);
  initUserHooks(service);

  return service;
};
`
}
