import { pascalSingular } from '../../../../../../utils/cases'
import * as R from 'ramda'
import {
  getEditComponent,
  getTsDefaultTypeValueExpression,
} from '../EntityEdit/DefaultEntityEdit'
import { getCompNamesToEditField } from '../../../../ui/componentNames/edit/getCompNamesToEditField'
import { EntityWideGenerationArgs } from '../../../../../args'
import { generatedWarning, pad1, pad6 } from '../../../../../utils'
import { getKeyField, isImageFileRef, isMarkdownField } from '../../../../../metaUtils'

export const uiDefaultCreateTmpl = ({
  allEntities,
  entity,
  options,
}: EntityWideGenerationArgs) => {
  const fileRefFields = entity.fields.filter(isImageFileRef)
  const withFileRef = fileRefFields.length > 0

  const fieldsToImport = entity.fields
    .filter((f) => !f.hidden)
    .filter((f) => !fileRefFields.includes(f))
    // .filter(f => f.requiredOnInput || f.requiredOnInput === null)
    .filter((f) => f.name !== 'id' || !getKeyField(entity).autoGenerated)
  const dateFieldsToImport = fieldsToImport.filter((f) =>
    ['datetime', 'date'].includes(f.type)
  )
  const notDateFieldsToImport = fieldsToImport.filter(
    (f) => !['datetime', 'date'].includes(f.type)
  )
  const reactAdminImports: string[] = [
    'useTranslate',
    'Create',
    'SimpleForm',
    'CreateProps',

    ...R.flatten(
      notDateFieldsToImport.map((f) => getCompNamesToEditField(f, allEntities))
    ),
  ]

  const hasHidden = entity.fields
    .filter((f) => !f.hidden)
    .filter((f) => f.name !== 'id')
    .some((f) => !(f.requiredOnInput || f.requiredOnInput === null))

  const fieldsToWorkWith = entity.fields
    .filter((f) => !f.hidden)

    // .filter(f => f.requiredOnInput || f.requiredOnInput === null)
    .filter((f) => f.name !== 'id' || !getKeyField(entity).autoGenerated)

  const initialValues = fieldsToWorkWith.filter((f) =>
    getTsDefaultTypeValueExpression(f)
  )

  return `/* eslint-disable max-len */
import React, {FC, useMemo, useCallback} from 'react';
import {
  ${R.uniq(reactAdminImports.map((el) => `${el},`)).join(`
  `)}
} from 'react-admin';${
    dateFieldsToImport.some((f) => f.type === 'datetime')
      ? `
import DateTimeInput from '../../../../uiLib/DateTimeInput';`
      : ''
  }${
    dateFieldsToImport.some((f) => f.type === 'date')
      ? `
import DateInput from '../../../../uiLib/DateInput';`
      : ''
  }${
    hasHidden
      ? `
import {useDebug} from '../../../../contexts/DebugContext';`
      : ''
  }
import {Grid} from '@mui/material';
import {yupResolver} from '@hookform/resolvers/yup';
import get${pascalSingular(entity.name)}Validation from '../get${pascalSingular(
    entity.name
  )}Validation';
import {SaveContext} from '../../../../contexts/SaveContext';
${
  withFileRef
    ? "import {FileInput} from '../../../../uiLib/file/FileInput';\n"
    : ''
}
${
  options.skipWarningThisIsGenerated
    ? ''
    : `// ${generatedWarning}
`
}
const Default${pascalSingular(
    entity.name
  )}Create: FC<CreateProps> = (props: CreateProps) => {
${
  hasHidden
    ? `  const {debug} = useDebug();
`
    : ''
}  const translate = useTranslate();

  const resolver = useMemo(() => yupResolver(get${pascalSingular(
    entity.name
  )}Validation(translate)), [translate]);

  return (
    <Create
      {...props}
      transform={useCallback((data: any) => ({
        ...data,${fieldsToWorkWith
          .filter((f) => ['datetime', 'date'].includes(f.type))
          .map(
            (f) => `
        ${f.name}: data.${f.name} || null,`
          )
          .join('')}
      }), [])}
    >
      <SaveContext>
        <SimpleForm
          defaultValues=${
            initialValues.length === 0
              ? '{{}}'
              : `{{
${initialValues
  .map((f) => `${f.name}: ${getTsDefaultTypeValueExpression(f)},`)
  .map(pad6)
  .join('\n')}
          }}`
        }
          resolver={resolver}
        >
          <Grid container spacing={2}>
${fieldsToWorkWith
  .map((f) => {
    const comp = `<Grid item ${isMarkdownField(f) ? 'xs={12} sm={12} md={12} lg={12}': 'xs={12} sm={6} md={3} lg={2}'}>
${pad1(getEditComponent(entity, allEntities, f, 'create'))}
</Grid>`

    const debuggedComp =
      f.requiredOnInput || f.requiredOnInput === null
        ? comp
        : `{debug && ${comp}}`

    return pad6(debuggedComp)
  })
  .join('\n')}
          </Grid>
        </SimpleForm>
      </SaveContext>
    </Create>
  );
};

export default Default${pascalSingular(entity.name)}Create;
`
}
