/* eslint-disable max-len */
import { ScalarFieldBuilder } from './fields/ScalarFieldBuilder'
import { IdFieldBuilder } from './fields/IdFieldBuilder'
import { LinkFieldBuilder } from './fields/LinkFieldBuilder'
import {EtityType, TKeyFieldType, Multitenancy, BaseSavableEntity} from './buildedTypes'
import CatalogBuilder from './CatalogBuilder'
import BaseBuilder from './BaseBuilder'
import { FormsBuilder } from './ui/FormsBuilder'
import { FieldBuilder } from './types'
import { ViewLinkFieldBuilder } from './fields/ViewLinkFieldBuilder'
import { pascal } from '../../utils/cases'
import * as R from 'ramda'

abstract class BaseSavableEntityBuilder extends BaseBuilder {
  id: IdFieldBuilder
  fields: FieldBuilder[] = []
  uniqueConstraints: string[][] = []
  type: EtityType = 'catalog'
  titleField: ScalarFieldBuilder | IdFieldBuilder
  deletable = false
  editable = true
  singleKey = true
  logging = false
  auditable = true
  creatableByUser = true
  updatableByUser = true
  removableByUser = true
  exportableByUser = true
  space = ''
  sortField = 'id'
  sortOrder: 'ASC' | 'DESC' = 'DESC'
  sybsystems: string[] = []
  forms?: FormsBuilder
  predefinedElements: Record<string, any>[] = []
  devPerefinedElements: Record<string, any>[] = []
  searchEnabled = true
  externalSearch = false
  multitenancy: Multitenancy = 'none'
  commonElementsVisibleToAll = false
  title: Record<string, {singular: string, plural: string}> = {}
  externalSearchName: string | undefined = undefined
  sharded = false
  isExternalSearch = false
  clearDBAfter: number | undefined
  allowedToChange: string = ''

  constructor(name: string, defaultLanguage: string, title?: {singular?: string, plural?: string}) {
    super(name, defaultLanguage, title)
    this.setTitle({plural: title?.plural ?? name, singular: title?.singular ?? title?.plural ?? name})

    this.id = new IdFieldBuilder('id', defaultLanguage)
      .setTitle('Id', 'en')
      .setTitle('Ид', 'ru')
    this.titleField = new IdFieldBuilder('id', defaultLanguage)

    this.setTitleFieldByName(this.getKey().name)
  }

  setTitle(title: {plural: string, singular: string}, language?: string) {
    const resultedLangiage = language ? language : this.defaultLanguage
    this.title[resultedLangiage] = title

    return this
  }

  setExternalSearch() {
    this.externalSearch = true
    this.getKey().setType('string').setAutoGenerated(true)
    this.externalSearchName = `external${pascal(this.name)}SearchTrackings`
    this.setSearchEnabled()

    return this
  }

  setSearchEnabled(searchEnabled?: boolean) {
    this.searchEnabled = searchEnabled ?? true

    const filed = this.getFieldIfExist('search');
    if (!searchEnabled && filed) {
      this.delField('search')
    }

    return this
  }

  setAuditable(auditable?: boolean) {
    this.auditable = auditable ?? true

    return this
  }

  setDeletable(deletable?: boolean) {
    this.deletable = deletable ?? true

    return this
  }
  setEditable(editable?: boolean) {
    this.editable = editable ?? true

    return this
  }
  setCreatableByUser(creatableByUser?: boolean) {
    this.creatableByUser = creatableByUser ?? true

    return this
  }
  setUpdatableByUser(updatableByUser?: boolean) {
    this.updatableByUser = updatableByUser ?? true

    return this
  }
  setRemovableByUser(removableByUser?: boolean) {
    this.removableByUser = removableByUser ?? true

    return this
  }
  setExportableByUser(exportableByUser?: boolean) {
    this.exportableByUser = exportableByUser ?? true

    return this
  }
  getKey() {
    if (!this.singleKey) {
      throw new Error('There is no single key')
    }

    return this.id
  }

  getShardedFields () {
    return this.fields.filter((f) => f.sharded)
  }

  getUniqueConstraints (registrarDependent = false): string[][] {
    const uniqKeys = this.getShardedFields().map(f => f.name)

    const isRegistrarDependentSumRegistry = this.type === 'sumRegistry' && registrarDependent;

    if (!isRegistrarDependentSumRegistry && !R.isEmpty(uniqKeys) && !R.equals(uniqKeys, ['id'])) {
      this.uniqueConstraints.push(uniqKeys);
    }

    return this.uniqueConstraints;
  }

  getFileds(): FieldBuilder[] {
    return [this.id, ...this.fields]
  }

  getFieldIfExist(name: string): FieldBuilder | undefined {
    return this.getFileds().find((f) => f.name === name);
  }

  getFiled(name: string): FieldBuilder {
    const filed = this.getFieldIfExist(name)
    if (!filed) {
      throw new Error(`There is no field with name "${name}"`)
    }

    return filed
  }

  getLinkFileds(): LinkFieldBuilder[] {
    return this.getFileds().filter(
      (field) => field.category === 'link'
    ) as LinkFieldBuilder[]
  }

  addField(
    name: string,
    title?: string,
    { isTitleField }: { isTitleField?: boolean } = {}
  ): ScalarFieldBuilder {
    if (this.fields.some((f) => f.name === name)) {
      throw new Error(
        `There is already field with name "${name}". Entity ${this.name}`
      )
    }

    const field = new ScalarFieldBuilder(name, this.defaultLanguage, title)
    this.fields.push(field)

    if (isTitleField) {
      this.setTitleFieldByName(name)
    }

    return field
  }

  delField(name: string) {
    this.fields = this.fields.filter((f) => f.name !== name)

    return this
  }

  addLinkField(
    e: string | CatalogBuilder,
    name: string,
    title?: string
  ): LinkFieldBuilder {
    let entity = e
    if (this.fields.some((f) => f.name === name)) {
      throw new Error(
        `There is already field with name "${name}". Entity ${this.name}`
      )
    }

    // get name from entity
    if (entity instanceof CatalogBuilder) {
      entity = entity.name
    }

    const field = new LinkFieldBuilder(
      entity,
      name,
      this.defaultLanguage,
      title
    )

    // get field type from entity
    if (e instanceof CatalogBuilder) {
      const entityType = e.fields.find(
        (field: FieldBuilder) => field instanceof IdFieldBuilder
      )?.type as TKeyFieldType | undefined

      if (entityType && field.type !== entityType) {
        field.setType(entityType)
      }
    }

    this.fields.push(field)

    return field
  }

  addFileField(name: string, title?: string): LinkFieldBuilder {
    const entity = 'files'
    if (this.fields.some((f) => f.name === name)) {
      throw new Error(
        `There is already field with name "${name}". Entity ${this.name}`
      )
    }

    const field = new LinkFieldBuilder(
      entity,
      name,
      this.defaultLanguage,
      title
    )
    field.setPredefinedLinkedEntity('file')

    this.fields.push(field)

    return field
  }

  addImageField(name: string, title?: string): LinkFieldBuilder {
    const entity = 'files'
    if (this.fields.some((f) => f.name === name)) {
      throw new Error(
        `There is already field with name "${name}". Entity ${this.name}`
      )
    }

    const field = new LinkFieldBuilder(
      entity,
      name,
      this.defaultLanguage,
      title
    )
    field.setPredefinedLinkedEntity('file')
    field.setFileType('image')

    this.fields.push(field)

    return field
  }

  addViewLinkField(
    e: string | CatalogBuilder,
    name: string,
    title?: string
  ): ViewLinkFieldBuilder {
    let entity = e
    if (this.fields.some((f) => f.name === name)) {
      throw new Error(
        `There is already field with name "${name}". Entity ${this.name}`
      )
    }

    // get name from entity
    if (entity instanceof CatalogBuilder) {
      entity = entity.name
    }

    const field = new ViewLinkFieldBuilder(
      entity,
      name,
      this.defaultLanguage,
      title
    )

    // get field type from entity
    if (e instanceof CatalogBuilder) {
      const entityType = e.fields.find(
        (field: FieldBuilder) => field instanceof IdFieldBuilder
      )?.type as TKeyFieldType | undefined

      if (entityType && field.type !== entityType) {
        field.setType(entityType)
      }
    }

    this.fields.push(field)

    return field
  }

  setTitleFieldByName(titleField: string) {
    const field = this.getFileds().find((f) => f.name === titleField) as
      | ScalarFieldBuilder
      | IdFieldBuilder
      | undefined
    if (!field) {
      throw new Error(
        `There is no field with name "${titleField}", you can not set it as a title field. Entity ${this.name}`
      )
    }

    this.titleField = field

    return this
  }

  setSort(field: string, order: 'ASC' | 'DESC') {
    if (!this.getFileds().some((f) => f.name === field)) {
      throw new Error(
        `There is no field with name "${field}", you can not set sort to this field. Entity ${this.name}`
      )
    }

    this.sortField = field
    this.sortOrder = order

    return this
  }

  addUniqueConstraint(fields: string[]): BaseSavableEntityBuilder {
    const currentFields = this.getFileds()

    // const currentRequiredFields = currentFields.filter(f => f.required);
    const currentFieldNames = currentFields.map((f) => f.name)

    // const currentRequiredFieldNames = currentRequiredFields.map(f => f.name);
    if (fields.some((f) => !currentFieldNames.includes(f))) {
      throw new Error(`You trying to add constraint for non existing field.
      Current fields: ${currentFields}, fields for constrain: ${fields}, field not in current: ${fields.filter(
        (f) => !currentFieldNames.includes(f)
      )}.
      Entity ${this.name}`)
    }

    // if (fields.some(f => !currentRequiredFieldNames.includes(f))) {
    //   throw new Error(`You trying to add constraint for not required field. Presence of not required filed breaks uniquiness check.
    //   Current required fields: ${currentFields}, fields for constrain: ${fields}, field not in current: ${fields.filter(f => !currentRequiredFieldNames.includes(f))}.
    //   Entity ${this.name}`);
    // }

    this.uniqueConstraints.push(fields)

    return this
  }

  build (): BaseSavableEntity {
    return {
      ...super.build(),
      title: this.title,
      singleKey: this.singleKey,
      // titleField: this.titleField.build(),
      titleField: this.titleField.name,
      // linkFields: this.getLinkFileds().map(f => f.build()),
      // keyField: this.getKey().build(),
      keyField: this.getKey().name,
      fields: this.getFileds().map((field) => field.build()),
      uniqueConstraints: this.getUniqueConstraints(),
      forms: this.getForms().build(),
      predefinedElements: this.predefinedElements,
      devPerefinedElements: this.devPerefinedElements,
      auditable: this.auditable,
      externalSearch: this.externalSearch,
      searchEnabled: this.searchEnabled,
      sortField: this.sortField,
      sortOrder: this.sortOrder,
      multitenancy: this.multitenancy,
      commonElementsVisibleToAll: this.commonElementsVisibleToAll,
      externalSearchName: this.externalSearchName,
      sharded: this.sharded,
      isExternalSearch: this.isExternalSearch,
      creatableByUser: this.creatableByUser,
      updatableByUser: this.updatableByUser,
      removableByUser: this.removableByUser,
      exportableByUser: this.exportableByUser,
      clearDBAfter: this.clearDBAfter,
      allowedToChange: this.allowedToChange,
    }
  }

  initFormas(): BaseSavableEntityBuilder {
    if (!this.forms) {
      this.forms = new FormsBuilder(() => this)
    }

    return this
  }

  getForms(): FormsBuilder {
    this.initFormas()

    return this.forms as FormsBuilder
  }

  addPredefinedElements(fields: Record<string, any>[]) {
    this.predefinedElements.push(...fields)
  }

  setPredefinedElements(fields: Record<string, any>[]) {
    this.predefinedElements = fields
  }

  addDevPredefinedElements(fields: Record<string, any>[]) {
    this.devPerefinedElements.push(...fields)
  }

  setDevPredefinedElements(fields: Record<string, any>[]) {
    this.devPerefinedElements = fields
  }

  setMultitenancy(
    multitenancy: Multitenancy,
    commonElementsVisibleToAll?: boolean
  ) {
    this.multitenancy = multitenancy

    if (
      multitenancy !== 'optional' &&
      commonElementsVisibleToAll !== undefined
    ) {
      throw new Error(
        `You are trying to specify commonElementsVisibleToAll, but multitenancy is not optional (${multitenancy})`
      )
    }

    this.commonElementsVisibleToAll =
      commonElementsVisibleToAll || multitenancy === 'optional'

    this.delField('tenantId')
    if (multitenancy !== 'none') {
      const tenantField = this.addLinkField('tenants', 'tenantId')
        .setType('int')
        .setNotUpdatableByUser()
      if (multitenancy === 'required') {
        tenantField
          .setRequired()
          .setNotUpdatableByUser(
            undefined,
            "await ctx.service('profile').getRequiredTenantId()"
          )
      }
    }
  }

  setSharded (value = true) {
    this.sharded = value

    return this
  }
  setIsExternalTable () {
    this.isExternalSearch = true
    return this
  }
  setClearDBAfter (days?: number) {
    if (!this.externalSearch) {
      throw new Error('You can only clear the database when it is synchronized with Elastic!')
    }

    this.clearDBAfter = days

    return this
  }
  setAllowedToChange (value: string = '') {
    this.allowedToChange = value

    return this
  }
}

export default BaseSavableEntityBuilder
