import { HttpMethod } from './curlTypes'
import { DocumentationOfDocument } from './docs/DocumentationOfDocument'
import { Forms } from './ui/Forms'

export type ConfigVarScope =
  | 'back'
  | 'admin-app'
  | 'cutomer-app'
  | 'worker'
  | 'telegramBot'

// {id: 'ui', title: 'Ui', gitSshTemplate: 'git@gitlab.com:mtbase/mtbase-ui.git', educational: false},
// {id: 'back', title: 'Back', gitSshTemplate: 'git@gitlab.com:mtbase/mtbase-back.git', educational: false},
// {id: 'app', title: 'App', gitSshTemplate: 'git@gitlab.com:mtbase/mtbase-app.git', educational: false},
// {id: 'land', title: 'Land', gitSshTemplate: 'git@gitlab.com:mtbase/mtbase-app.git', educational: false},
// {id: 'learningBaseTs', title: 'Учебный Базовый Ts', gitSshTemplate: 'git@gitlab.com:js-learning/nodets-template.git', educational: true},
// {id: 'learningReact', title: 'Учебный React', gitSshTemplate: 'git@gitlab.com:js-learning/react-template.git', educational: true},
// {id: 'learningFigma', title: 'Учебный Figma', gitSshTemplate: 'git@gitlab.com:js-learning/nodets-template.git', educational: true},

export interface ConfigVar {
  name: string
  default: string
  needFor: string
  scopes: ConfigVarScope[]
}

export interface Glossary {
  term: string
  definition: string
}

export type ProjectCategory = 'back' | 'ui' | 'app' | 'land'

export interface Command {
  projectCategory: ProjectCategory
  name: string
  command: string
  needFor: string
}

export type TKeyFieldType = 'string' | 'int' | 'bigint'
export type FiledType =
  | 'string'
  | 'int'
  | 'bigint'
  | 'float'
  | 'bool'
  | 'datetime'
  | 'date'
export type Meaning = 'img'

export enum TsTypes {
  Number = 'number',
  BigInt = 'bigint',
  String = 'string',
  Boolean = 'boolean',
  Date = 'Date',
}

export type DefaultDbValue = string | boolean | undefined

type BaseField = {
  name: string
  title: Record<string, string>
  needFor: string
  updatable: boolean
  required: boolean
  requiredOnInput: boolean | null
  updatableByUser: boolean
  hidden?: boolean
  searchable?: boolean
  showInList: boolean
  showInCreate: boolean
  showInEdit: boolean
  defaultDbValue: DefaultDbValue
  defaultValueExpression?: string
  defaultBackendValueExpression?: string
}

type ScalarBaseField = BaseField & {
  category: 'scalar'
}

type IdBaseField = BaseField & {
  autoGenerated: boolean
  category: 'id'
}

type LinkMainBaseField = BaseField & {
  externalEntity: string
  category: 'link'
}

export type PredefinedLinkedEntity = 'none' | 'file'

type NotPredefinedLinkBaseField = LinkMainBaseField & {
  predefinedLinkedEntity: 'none'
}

export type FileType = 'plain' | 'image'

type FilePredefinedLinkBaseField = LinkMainBaseField & {
  predefinedLinkedEntity: 'file'
  fileType: FileType
}

type LinkBaseField = NotPredefinedLinkBaseField | FilePredefinedLinkBaseField

export type ConstantOnCreateDate = false | 'now'
export type ConstantOnUpdateDate = false | 'now'

export type DateTimeField = ScalarBaseField & {
  type: 'datetime'
  constantOnCreate: ConstantOnCreateDate
  constantOnUpdate: ConstantOnUpdateDate
}

export type DateField = ScalarBaseField & {
  type: 'date'
  constantOnCreate: ConstantOnCreateDate
  constantOnUpdate: ConstantOnUpdateDate
}

export type ConstantOnCreateInt = false | 'currentUser'
export type ConstantOnUpdateInt = false | 'currentUser'

export type ConstantOnCreate = ConstantOnCreateInt | ConstantOnCreateDate
export type ConstantOnUpdate = ConstantOnUpdateInt | ConstantOnUpdateDate

export type IntField = ScalarBaseField & {
  type: 'int'
  constantOnCreate: ConstantOnCreateInt
  constantOnUpdate: ConstantOnUpdateInt
}

export type BigIntField = ScalarBaseField & {
  type: 'bigint'
  constantOnCreate: ConstantOnCreateInt
  constantOnUpdate: ConstantOnUpdateInt
}

export type BaseStringField = ScalarBaseField & {
  type: 'string'
}

export type StringType = 'plain' | 'multiline' | 'richEdit'

export type PlainStringField = BaseStringField & {
  stringType: 'plain'
}

export type MultilineStringField = BaseStringField & {
  stringType: 'multiline'
}

export type MarkdownStringField = BaseStringField & {
  stringType: 'markdown'
}

export type RichEditStringField = BaseStringField & {
  stringType: 'richEdit'
}

export type StringField =
  | PlainStringField
  | MultilineStringField
  | MarkdownStringField
  | RichEditStringField

export type FloatField = ScalarBaseField & {
  type: 'float'
}

export type BoolField = ScalarBaseField & {
  type: 'bool'
}

export type BigIntIdField = IdBaseField & Omit<BigIntField, 'category'>
export type IntIdField = IdBaseField & Omit<IntField, 'category'>
export type StringIdField = IdBaseField & Omit<StringField, 'category'>

export type IntLinkField = LinkBaseField & { type: 'int' }
export type BigIntLinkField = LinkBaseField & { type: 'bigint' }
export type StringLinkField = LinkBaseField & { type: 'string' }

export type ScalarField =
  | DateTimeField
  | DateField
  | IntField
  | BigIntField
  | StringField
  | FloatField
  | BoolField

export type GeneralLinkField = BigIntLinkField | IntLinkField | StringLinkField
export type EntityLinkField = GeneralLinkField & { linkCategory: 'entity' }
export type ViewLinkField = GeneralLinkField & { linkCategory: 'view' }
export type LinkField = EntityLinkField | ViewLinkField

export type IdField = IntIdField | BigIntIdField | StringIdField

export type Field = ScalarField | LinkField | IdField | ViewLinkField

export type Multitenancy = 'none' | 'optional' | 'required'

export type BaseEntity = {
  name: string
  title: Record<string, string>
  needFor: Record<string, string>
  materialUiIcon: string
}

export type BaseSavableEntity = BaseEntity & {
  // titleField: Field;
  titleField: string
  keyField: string
  // keyField: IdField;
  singleKey: boolean
  fields: Field[]
  // linkFields: LinkField[];
  uniqueConstraints: string[][]
  forms: Forms
  predefinedElements: Record<string, any>[]
  devPerefinedElements: Record<string, any>[]
  auditable: boolean
  externalSearch: boolean
  sortField: string
  sortOrder: 'ASC' | 'DESC'
  multitenancy: Multitenancy
  commonElementsVisibleToAll: boolean
}

export type Report = BaseEntity & {
  type: 'report'
}

export type Document = BaseSavableEntity & {
  type: 'document'
  deletable: boolean
  editable: boolean
  registries: string[]
  documentation: DocumentationOfDocument
}

export type Catalog = BaseSavableEntity & {
  type: 'catalog'
  deletable: boolean
  editable: boolean
}

export type Role = BaseEntity & {
  type: 'role'
}

export type TelegramBot = BaseEntity & {
  type: 'telegramBot'
}

export type RestApiMethod = BaseEntity & {
  type: 'restApiMethod'
  note: string
  httpMethod: HttpMethod
  path: string
  urlExample?: string
  requestExample: Record<string, any>
  successResponseExample: Record<string, any>
  errorResponseExample: Record<string, any>
}

export type RestApi = BaseEntity & {
  type: 'restApi'
  methods: RestApiMethod[]
  path: string
}

export type MemoryAndCpu = {
  memory: string
  cpu: string
}

export type Worker = BaseEntity & {
  requests: MemoryAndCpu
  limits: MemoryAndCpu
}

export type InfoRegistryPeriod =
  | 'notPeriodic'
  | 'second'
  | 'day'
  | 'month'
  | 'year'

export type InfoRegistry = BaseSavableEntity & {
  type: 'infoRegistry'
  registrarDepended: boolean
  dimensions: Field[]
  resources: Field[]
  period: InfoRegistryPeriod
}

export type SumRegistry = BaseSavableEntity & {
  type: 'sumRegistry'
  registrarDepended: boolean
  dimensions: Field[]
  resources: Field[]
}

export type Entity = Document | Catalog | InfoRegistry | SumRegistry

export interface DeployEnvironment {
  name: string
  clusterName: string
}

export type Back = {
  requests: MemoryAndCpu
  limits: MemoryAndCpu
}

export type System = {
  name: string
  prefix: string
  needFor: string
  configVars: ConfigVar[]
  catalogs: Catalog[]
  documents: Document[]
  infoRegistries: InfoRegistry[]
  sumRegistries: SumRegistry[]
  languages: string[]
  defaultLanguage: string
  roles: Role[]

  reports: Report[]
  telegramBots: TelegramBot[]
  deployEnvironments: DeployEnvironment[]
  commands: Command[]
  glossary: Glossary[]
  restApis: RestApi[]
  workers: Worker[]

  back: Back
}

export type EtityType = 'catalog' | 'document' | 'infoRegistry' | 'sumRegistry'
